---
title: "General bcbio coverage report"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: readable
    highlight: zenburn
---

```{r opt,cache=FALSE}
library(knitr)
library(rmarkdown)
knitr::opts_chunk$set(tidy=TRUE, highlight=TRUE, dev="png",
                      cache=FALSE, highlight=TRUE, autodep=TRUE, 
                      warning=FALSE, error=FALSE,
                      eval=TRUE, fig.width= 9, echo=FALSE,
                      verbose=FALSE,
                      message=FALSE, prompt=TRUE, comment='', fig.cap='', bootstrap.show.code=FALSE)

```

```{r custom, results='hide'}
library(ggplot2)
library(pheatmap)
library(scales)
library(gridExtra)
library(gtools)
library(RColorBrewer)
library(knitr)
library(tidyr)
library(reshape2)
library(rmarkdown)
library(dplyr)
library(DT)

number_ticks <- function(n) {function(limits) pretty(limits, n)}
options(bitmapType = 'cairo')

path_results = getwd()
```

```{r create-report, echo=FALSE, eval=FALSE}
render(file.path(path_results, "report-ready.Rmd"))
```

